import type { SpotWithRelations } from "./types";

const WP = "https://pub-7d430b8241bc4d38b717b9e2905120d8.r2.dev/uploads";

/** ヘルパー: SpotWithRelations の共通デフォルト値 */
function spot(
  overrides: Partial<SpotWithRelations> & {
    id: string;
    slug: string;
    title: string;
    type: "hotel" | "spot" | "event";
  }
): SpotWithRelations {
  return {
    category_id: "dummy-minato",
    content: null,
    name: overrides.title,
    lead: null,
    report: null,
    address: null,
    official_url: null,
    official_label: null,
    sns_url: null,
    sns_label: null,
    relation_url: null,
    relation_label: null,
    hours: null,
    holiday: null,
    money: null,
    station: null,
    parking: null,
    map: null,
    height: null,
    movie: null,
    asoview: null,
    asoview_02: null,
    latitude: null,
    longitude: null,
    rating_beautiful: null,
    rating_access: null,
    rating_atmosphere: null,
    rating_cost: null,
    featured_image: null,
    published: true,
    closed: false,
    published_at: "2024-08-01T00:00:00+09:00",
    created_at: "2024-08-01T00:00:00+09:00",
    updated_at: "2025-02-23T00:00:00+09:00",
    category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
    tags: [],
    images: [],
    faqs: [],
    reviews: [],
    hotel: null,
    event: null,
    ...overrides,
  };
}

/** アフィリエイトリンク（ダミー） */
const aff = {
  rakuten: '<a class="panelLink-rakuten" href="#" rel="nofollow">楽天トラベルで予約する</a>',
  booking: '<a class="panelLink-booking" href="#" rel="nofollow">Booking.comで予約する</a>',
  jaran: '<a class="panelLink-jaran" href="#" rel="nofollow">じゃらんnetで予約する</a>',
  ikkyu: '<a class="panelLink-ikkyu" href="#" rel="nofollow">一休.comで予約する</a>',
};

export const dummyTagSpots: Record<string, SpotWithRelations[]> = {
  "tokyo-tower": [
    // ========== ホテル ==========
    spot({
      id: "dummy-prince",
      slug: "the-prince-park-tower-tokyo",
      title: "ザ・プリンス パークタワー東京",
      type: "hotel",
      address: "東京都港区芝公園 4-8-1",
      featured_image: `${WP}/2023/01/prince-hotel-room-02.jpg`,
      station:
        '<ul><li>JR線「浜松町駅」から徒歩12分</li><li>浅草線・大江戸線「大門駅」A6出口から徒歩9分</li><li>大江戸線「赤羽橋駅」赤羽橋口から徒歩2分</li><li>三田線「芝公園駅」A4出口から徒歩3分</li></ul>',
      rating_beautiful: 5,
      rating_access: 5,
      rating_atmosphere: 5,
      rating_cost: 3,
      hotel: {
        id: "h-prince",
        spot_id: "dummy-prince",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-andaz",
      slug: "andaz-tokyo-toranomon-hills",
      title: "アンダーズ東京 虎ノ門ヒルズ",
      type: "hotel",
      address: "東京都港区虎ノ門 1-23-4",
      featured_image: `${WP}/2023/01/underz-tokyo-09.jpg`,
      station:
        '<ul><li>日比谷線「虎ノ門ヒルズ駅」より徒歩約3分</li><li>銀座線「虎ノ門駅」地下鉄歩行者通路経由で徒歩約5分</li><li>千代田線・丸の内線「霞ヶ関駅」A12番出口より徒歩約8分</li><li>三田線「内幸町駅」A3番出口より徒歩約8分</li></ul>',
      rating_beautiful: 5,
      rating_access: 4,
      rating_atmosphere: 5,
      rating_cost: 2,
      hotel: {
        id: "h-andaz",
        spot_id: "dummy-andaz",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-parkhotel",
      slug: "park-hotel-tokyo",
      title: "パークホテル東京",
      type: "hotel",
      address: "東京都港区東新橋 1-71 汐留メディアタワー",
      featured_image: `${WP}/2023/03/park-hotel-tokyo-view.jpg`,
      station:
        '<ul><li>JR、東京メトロ・都営地下鉄「新橋駅」より徒歩約7分</li><li>都営地下鉄大江戸線、ゆりかもめ線「汐留」駅より徒歩1分</li></ul>',
      rating_beautiful: 4,
      rating_access: 5,
      rating_atmosphere: 4,
      rating_cost: 3,
      hotel: {
        id: "h-parkhotel",
        spot_id: "dummy-parkhotel",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-creston",
      slug: "ginza-crestonhotel",
      title: "銀座クレストン",
      type: "hotel",
      address: "東京都中央区明石町8 聖路加ガーデン",
      featured_image: `${WP}/2025/02/restaurant-luke-3-1.jpg`,
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
      station:
        '<ul><li>東京メトロ日比谷線「築地」駅より徒歩約7分</li><li>東京メトロ有楽町線「新富町」駅より徒歩約8分</li></ul>',
      rating_beautiful: 4,
      rating_access: 3,
      rating_atmosphere: 4,
      rating_cost: 3,
      hotel: {
        id: "h-creston",
        spot_id: "dummy-creston",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),

    // ========== 展望台 ==========
    spot({
      id: "dummy-tcv",
      slug: "tokyo-city-view",
      title: "六本木ヒルズ展望台 東京シティビュー",
      type: "spot",
      address: "東京都港区六本木 6-10-1",
      featured_image: `${WP}/2023/01/tokyo-city-view-02.jpg`,
      money: "一般 2,200円 / 学生 1,400円 / 子供 900円 / シニア 1,900円",
      height: "250メートル",
      hours: "東京シティビュー 10:00～22:00 / スカイデッキ 11:00～20:00",
      station:
        '<ul><li>日比谷線「六本木駅」1C出口から徒歩3分</li><li>大江戸線「六本木駅」3出口から徒歩6分</li><li>大江戸線「麻布十番駅」7出口から徒歩9分</li><li>千代田線「乃木坂駅」5出口から徒歩10分</li></ul>',
    }),
    spot({
      id: "dummy-azabudai",
      slug: "azabudai-hills",
      title: "麻布台ヒルズ スカイロビー",
      type: "spot",
      address: "東京都港区麻布台 1-3-1",
      featured_image: `${WP}/2023/12/azabudai-hills-4.jpg`,
      money: "レストラン / カフェの利用が必須",
      hours: "平日：10時～21時、休日：9時～21時",
      station:
        '<ul><li>東京メトロ南北線「六本木一丁目駅」2番出口 徒歩4分</li><li>東京メトロ日比谷線「神谷町駅」5番出口 直結</li><li>東京メトロ日比谷線「六本木駅」3番出口 徒歩10分</li><li>都営大江戸線「六本木駅」5番出口 徒歩10分</li></ul>',
    }),
    spot({
      id: "dummy-shibuyasky",
      slug: "shibuya-sky",
      title: "渋谷スカイ 渋谷スクランブルスクエア 展望台",
      type: "spot",
      address: "東京都渋谷区渋谷 2-24-12",
      featured_image: `${WP}/2023/01/shibuya-sky-6-1.jpg`,
      money: "大人 14:59まで 2,700円 / 15:00以降 3,400円 / 小人 1,200円",
      height: "約230m",
      hours: "10:00 - 22:30（最終入場 21:20）",
      station: '<ul><li>渋谷駅から直結</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-ebisu",
      slug: "ebis-garden-place-sky-lounge",
      title: "恵比寿ガーデンプレイス 展望台 Top of Yebis",
      type: "spot",
      address: "東京都渋谷区恵比寿 4-20",
      featured_image: `${WP}/2023/01/ebis-garden-place-tokyo-tower-01.jpg`,
      money: "無料",
      height: "167m",
      hours: "11:00～23:30",
      station:
        '<ul><li>JR山手線「恵比寿駅」から徒歩5分</li><li>東京メトロ日比谷線「恵比寿駅」から徒歩7分</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-hachitama",
      slug: "hachitama-observatory",
      title: "球体展望室 はちたま",
      type: "spot",
      address: "東京都港区台場 2-4-8",
      featured_image: `${WP}/2023/01/hachitama-rainbow.jpg`,
      money: "一般 700円 / 小中学生 450円",
      height: "100メートル",
      hours: "10:00～18:00",
      station:
        '<ul><li>ゆりかもめ線「お台場駅」から徒歩約3分</li><li>りんかい線「東京テレポート駅」から徒歩約5分</li></ul>',
    }),
    spot({
      id: "dummy-telecom",
      slug: "telecom-center",
      title: "テレコムセンター展望台",
      type: "spot",
      address: "東京都江東区青海 2-5-10",
      featured_image: `${WP}/2023/02/telecom-center-05.jpg`,
      money: "大人500円 / 子供300円",
      height: "99ｍ",
      hours: "平日 15:00～20:00 / 休日 11:00～20:00",
      station: '<ul><li>ゆりかもめ線「テレコムセンター駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-skytree",
      slug: "tokyo-sky-tree",
      title: "東京スカイツリー 展望回廊&展望デッキ",
      type: "spot",
      address: "東京都墨田区押上 1-1-2",
      featured_image: `${WP}/2023/02/tokyo-skytree-1.jpg`,
      money: "土日 天望回廊1,100円 / 天望デッキ2,300円 / セット券3,400円\n平日 天望回廊1,000円 / 天望デッキ2,100円 / セット券3,100円",
      height: "展望回廊 450m、展望デッキ 350m",
      hours: "10:00～21:00（最終入場 20:00）",
      station:
        '<ul><li>都営地下鉄「押上」駅から徒歩1分</li><li>東武線「とうきょうスカイツリー」駅から徒歩6分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),

    // ========== 広場・公園 ==========
    spot({
      id: "dummy-stairs",
      slug: "tokyo-tower-stairs",
      title: "東京タワー 地下駐車場の階段",
      type: "spot",
      address: "東京都港区芝公園 4-5",
      featured_image: `${WP}/2024/01/tokyo-tower-stair-7.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>大江戸線 赤羽橋駅・赤羽橋口から徒歩5分</li><li>日比谷線 神谷町駅・1番出口から徒歩7分</li><li>三田線 御成門駅・A1から徒歩6分</li><li>三田線 芝公園駅・A4から徒歩10分</li></ul>',
    }),
    spot({
      id: "dummy-zojoji",
      slug: "zojyoji",
      title: "増上寺",
      type: "spot",
      address: "東京都港区芝公園4-7-35",
      featured_image: `${WP}/2023/01/tokyo-tower-3.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>都営地下鉄三田線「御成門駅」から徒歩3分</li><li>都営地下鉄三田線「芝公園」から徒歩3分</li><li>都営地下鉄浅草線・大江戸線「大門駅」から徒歩5分</li></ul>',
    }),
    spot({
      id: "dummy-fudanotsuji",
      slug: "fudanotsuji",
      title: "札の辻橋歩道橋",
      type: "spot",
      address: "東京都港区三田3丁目周辺",
      featured_image: `${WP}/2023/01/fudanotsuj-01.jpg`,
      money: "無料",
      hours: "24時間",
      station: '<ul><li>JR「田町駅」から徒歩約3分</li></ul>',
    }),
    spot({
      id: "dummy-shiba01",
      slug: "minato-park-1",
      title: "芝公園1号地",
      type: "spot",
      address: "東京都港区芝公園 4-10-17",
      featured_image: `${WP}/2023/03/shiba-park-02.jpg`,
      money: "無料",
      hours: "24時間",
      station:
        '<ul><li>JR「浜松町駅」から徒歩約12分</li><li>三田線「芝公園駅」I05出口から徒歩2分</li><li>三田線「御成門駅」I06出口から徒歩2分</li><li>大江戸線「赤羽橋駅」E21出口から徒歩2分</li><li>浅草線「大門駅」E20出口から徒歩5分</li></ul>',
    }),
    spot({
      id: "dummy-shiba04",
      slug: "shiba-park-04",
      title: "芝公園4号地",
      type: "spot",
      address: "東京都港区芝公園 3-2",
      featured_image: `${WP}/2023/01/shiba-park-04-02.jpg-22-57-38-891.jpg`,
      money: "無料",
      hours: "終日開放",
      station: '<ul><li>都営三田線「御成門駅・A6出口」から徒歩約1分</li></ul>',
    }),
    spot({
      id: "dummy-garden",
      slug: "prince-park-tower-tokyo-ground",
      title: "プリンスパークタワー東京 空中庭園",
      type: "spot",
      address: "東京都港区芝公園4-8-1",
      featured_image: `${WP}/2023/03/prince-hotel-park-02.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>地下鉄大江戸線「赤羽橋駅」から徒歩2分</li><li>地下鉄三田線「芝公園駅」から徒歩3分</li><li>JR線「浜松町駅」から徒歩12分</li></ul>',
    }),
    spot({
      id: "dummy-tsukiji",
      slug: "tsukiji-bridge",
      title: "築地大橋",
      type: "spot",
      address: "東京都中央区築地5丁目",
      featured_image: `${WP}/2023/10/tsukiji-bridge-1.jpg`,
      money: "無料",
      hours: "終日開放",
      station: '<ul><li>都営大江戸線「勝どき駅」から徒歩約10分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
    }),
    spot({
      id: "dummy-shinagawa",
      slug: "shinagawa-season-terrace",
      title: "品川シーズンテラス",
      type: "spot",
      address: "東京都港区港南 1-2-70",
      featured_image: `${WP}/2023/03/shinagawa-season-terrace-5.jpg`,
      money: "無料",
      hours: "7:00～23:00",
      station:
        '<ul><li>JR品川駅 港南口より徒歩6分</li><li>京浜急行電鉄品川駅 高輪口より徒歩9分</li></ul>',
    }),
    spot({
      id: "dummy-rainbow",
      slug: "rainbow-bridge-promenade",
      title: "レインボーブリッジ遊歩道（プロムナード）",
      type: "spot",
      address: "東京都港区海岸 3-33-19",
      featured_image: `${WP}/2023/03/rainbow-bridge-promenade-night-02.jpg`,
      money: "無料",
      hours: "4月～10月 9:00～21:00 / 11月～3月 10:00～18:00",
      station: '<ul><li>ゆりかもめ線「芝浦ふ頭駅」から徒歩約5分</li></ul>',
    }),
    spot({
      id: "dummy-keyakizaka",
      slug: "roppongi-keyaki-street",
      title: "六本木けやき坂通り",
      type: "spot",
      address: "東京都港区六本木 6-12",
      featured_image: `${WP}/2023/01/ropponngi-keyaki-street-05.jpg`,
      money: "無料",
      hours: "日没から23時まで",
      station:
        '<ul><li>東京メトロ 日比谷線「六本木駅」1出口から徒歩約0分（コンコースにて直結）</li><li>都営地下鉄 大江戸線「六本木駅」3出口から徒歩約4分</li><li>都営地下鉄 大江戸線「麻布十番駅」7出口から徒歩約4分</li></ul>',
    }),
    spot({
      id: "dummy-chidorigafuchi",
      slug: "chidorigabuchi",
      title: "千鳥ヶ淵緑道",
      type: "spot",
      address: null,
      featured_image: `${WP}/2023/03/chidorigabuchi-3.jpg`,
      money: null,
      hours: null,
      station: null,
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-under",
      slug: "tokyo-tower-stairs",
      title: "東京タワーの真下",
      type: "spot",
      address: "東京都港区芝公園 4-2-8",
      featured_image: `${WP}/2023/01/tokyo-tower-under-1.jpg`,
      money: "大人1,200円 / 高校生1,000円 / 小中学生700円 / 未就学児500円",
      height: "メインデッキ 150m、トップデッキ 250m",
      hours: "9:00~22:30（最終入場 22:00）",
      station:
        '<ul><li>大江戸線 赤羽橋駅・赤羽橋口から徒歩5分</li><li>日比谷線 神谷町駅・1番出口から徒歩7分</li><li>三田線 御成門駅・A1から徒歩6分</li><li>三田線 芝公園駅・A4から徒歩10分</li></ul>',
    }),
  ],

  /* ================================================================ */
  /* 東京スカイツリー                                                  */
  /* ================================================================ */
  "tokyo-sky-tree": [
    // ========== ホテル ==========
    spot({
      id: "dummy-wing-asakusa",
      slug: "wing-international-select-asakusa-komagata",
      title: "ウィングインターナショナルセレクト浅草駒形",
      type: "hotel",
      address: "東京都台東区駒形 2-7-5",
      featured_image: `${WP}/2023/02/wing-inter-national-asakusa-5.jpg`,
      station:
        '<ul><li>都営浅草線 浅草駅A2Bエレベーター出口から徒歩0分</li></ul>',
      rating_beautiful: 4,
      rating_access: 5,
      rating_atmosphere: 4,
      rating_cost: 4,
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "h-wing-asakusa",
        spot_id: "dummy-wing-asakusa",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-asakusa-view",
      slug: "asakusa-view-hotel",
      title: "浅草ビューホテル",
      type: "hotel",
      address: "東京都台東区西浅草 3-17-1",
      featured_image: `${WP}/2023/07/asakusa-view-8.jpg`,
      station:
        '<ul><li>つくばエキスプレス「浅草駅」直結</li><li>東京メトロ銀座線「田原町駅」徒歩７分</li><li>東京メトロ銀座線「浅草駅」徒歩10分</li></ul>',
      rating_beautiful: 4,
      rating_access: 4,
      rating_atmosphere: 4,
      rating_cost: 3,
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "h-asakusa-view",
        spot_id: "dummy-asakusa-view",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-kanzashi",
      slug: "the-kanzashi-tokyo-asakusa",
      title: "THE KANZASHI TOKYO ASAKUSA",
      type: "hotel",
      address: "東京都台東区浅草２丁目２７−１０",
      featured_image: `${WP}/2024/08/kanzashi-asakusa-hotel-9.jpg`,
      station:
        '<ul><li>つくばエクスプレス「浅草駅」A出口より徒歩7分</li><li>東京メトロ銀座線「浅草駅」A4出口より徒歩10分</li><li>都営地下鉄浅草線「浅草駅」A4出口より徒歩12分</li></ul>',
      rating_beautiful: 4,
      rating_access: 4,
      rating_atmosphere: 4,
      rating_cost: 5,
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "h-kanzashi",
        spot_id: "dummy-kanzashi",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-gate-hotel",
      slug: "the-gate-hotel-kaminarimon-gate-by-hulic",
      title: "The Gate Hotel 雷門 by HULIC",
      type: "hotel",
      address: "東京都台東区雷門2-16-11",
      featured_image: `${WP}/2023/07/the-gate-hotel-5.jpg`,
      station:
        '<ul><li>銀座線「浅草駅」・出口２から徒歩で約2分</li><li>都営浅草線「浅草駅」出口A４から徒歩で約3分</li></ul>',
      rating_beautiful: 4,
      rating_access: 5,
      rating_atmosphere: 4,
      rating_cost: 3,
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "h-gate-hotel",
        spot_id: "dummy-gate-hotel",
        checkin: "14:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-interconti-bay",
      slug: "interconti-tokyo-bay",
      title: "インターコンチネンタル東京ベイ",
      type: "hotel",
      address: "東京都港区海岸 1-16-2",
      featured_image: `${WP}/2023/08/interconti-tokyo-bay-12.jpg`,
      station:
        '<ul><li>新交通ゆりかもめ「竹芝駅」直結</li><li>JR・モノレール「浜松町駅」より徒歩8分</li><li>都営大江戸線・浅草線「大門駅」より徒歩10分</li></ul>',
      rating_beautiful: 4,
      rating_access: 4,
      rating_atmosphere: 5,
      rating_cost: 2,
      hotel: {
        id: "h-interconti-bay",
        spot_id: "dummy-interconti-bay",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),

    // ========== 展望台 ==========
    spot({
      id: "dummy-funabori",
      slug: "towerhall-funabori",
      title: "タワーホール船堀",
      type: "spot",
      address: "東京都江戸川区船堀 4-1-1",
      featured_image: `${WP}/2023/02/towerha-ll-funabori-skytree.jpg`,
      money: "無料",
      height: "103m",
      hours: "展望エレベーター運行時間：9：00 ~ 21：30",
      station:
        '<ul><li>都営新宿線「船堀駅」から徒歩約1分</li></ul>',
      category: { id: "dummy-edogawa", name: "江戸川区", slug: "edogawa", created_at: "" },
      category_id: "dummy-edogawa",
    }),
    spot({
      id: "dummy-east-tower-30f",
      slug: "tokyo-skytree-east-tower",
      title: "スカイツリーイーストタワー30F展望台",
      type: "spot",
      address: "東京都墨田区押上1-1-２",
      featured_image: `${WP}/2023/01/tokyo-sky-tree-east-tower-00.jpg`,
      money: "無料",
      hours: "11：00～23：00",
      station:
        '<ul><li>都営地下鉄「押上」駅から徒歩1分</li><li>東武線「とうきょうスカイツリー」駅から徒歩6分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-hareterrace",
      slug: "asakusa-ekimise",
      title: "浅草EKIMISE 浅草ハレテラス",
      type: "spot",
      address: "東京都台東区花川戸 1-4",
      featured_image: `${WP}/2023/12/asakusa-hare-terrace-1.jpg`,
      money: "無料",
      hours: "10:00 ~ 20:00",
      station:
        '<ul><li>東武伊勢崎線（東武スカイツリーライン）「浅草駅」直結</li><li>東京メトロ銀座線「浅草駅」約1分</li><li>都営浅草線「浅草駅」約3分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
    }),
    spot({
      id: "dummy-arcakit",
      slug: "arcakit",
      title: "アルカキット錦糸町",
      type: "spot",
      address: "東京都墨田区錦糸 2-2-1",
      featured_image: `${WP}/2024/01/arcakit-8.jpg`,
      money: "無料",
      hours: "10:00～18:00（レストランフロアは11:00～22:30）",
      station:
        '<ul><li>JR総武線「錦糸町駅」北口よりすぐ</li><li>東京メトロ半蔵門線「錦糸町駅」3番出口から徒歩1分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-asakusa-tourist",
      slug: "asakusa-cultural-tourism-center",
      title: "浅草文化観光センター",
      type: "spot",
      address: "東京都台東区雷門 2-18-9",
      featured_image: `${WP}/2023/02/asakusabunka-terrace-06.jpg`,
      money: "無料",
      hours: "9:00～22:00",
      station:
        '<ul><li>東武伊勢崎線（東武スカイツリーライン）浅草駅から徒歩5分</li><li>東京メトロ銀座線「浅草駅」出口2から徒歩1分</li><li>都営浅草線「浅草駅」A4出口から徒歩2分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
    }),
    spot({
      id: "dummy-asahi-sky",
      slug: "asahi-skyroom",
      title: "展望ラウンジ アサヒスカイルーム",
      type: "spot",
      address: "東京都墨田区吾妻橋１丁目２３−１ アサヒグループ本社ビル ２２階",
      featured_image: `${WP}/2025/12/asakusa-14.jpg`,
      money: "1ドリンク制",
      height: "100m",
      hours: "10:00 - 22:00",
      station:
        '<ul><li>東京メトロ銀座線「浅草」より徒歩約3分</li><li>都営浅草線「浅草」・「本所吾妻橋」より徒歩5分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-bunkyo-civic",
      slug: "civic-bunkyo",
      title: "文京シビックセンター 展望台",
      type: "spot",
      address: "東京都文京区春日 1-16-21",
      featured_image: `${WP}/2023/12/civic-bunkyo-13.jpg`,
      money: "無料",
      height: "約105m",
      hours: "9:00～20:30",
      station:
        '<ul><li>東京メトロ丸ノ内線・南北線「後楽園」駅より徒歩1分</li><li>都営三田線・大江戸線「春日」駅より徒歩1分</li><li>JR総武線「水道橋」駅より徒歩9分</li></ul>',
      category: { id: "dummy-bunkyo", name: "文京区", slug: "bunkyo", created_at: "" },
      category_id: "dummy-bunkyo",
    }),
    spot({
      id: "dummy-sunshine60",
      slug: "sunshine-60",
      title: "サンシャイン60 展望台 てんぼうパーク",
      type: "spot",
      address: "東京都豊島区東池袋 3-1-1",
      featured_image: `${WP}/2023/07/sunshine-60-9.jpg`,
      money: "大人（高校生以上）700円～1,200円 / 小中学生 500円～800円",
      height: "251m",
      hours: "11:00 〜 21:00",
      station:
        '<ul><li>池袋駅（JR・東京メトロ・西武線・東武線）35番出口より徒歩約8分</li><li>東池袋駅（東京メトロ有楽町線）6・7番出口より地下通路で徒歩約3分</li></ul>',
      category: { id: "dummy-toshima", name: "豊島区", slug: "toshima", created_at: "" },
      category_id: "dummy-toshima",
    }),
    spot({
      id: "dummy-kitatopia",
      slug: "kitatopia",
      title: "北とぴあ展望ロビー",
      type: "spot",
      address: "東京都北区王子 1-11−1",
      featured_image: `${WP}/2023/02/kita-topia-night-03.jpg`,
      money: "無料",
      height: "80m",
      hours: "8:30 ~ 22:00",
      station:
        '<ul><li>東京メトロ南北線 王子 ５番出口 直結</li><li>京浜東北線 王子 北口 徒歩 2分</li><li>都電荒川線 王子駅前 徒歩 5分</li></ul>',
      category: { id: "dummy-kita", name: "北区", slug: "kita", created_at: "" },
      category_id: "dummy-kita",
    }),
    spot({
      id: "dummy-ilink",
      slug: "ilink-town",
      title: "アイ・リンクタウン展望施設",
      type: "spot",
      address: "千葉県市川市市川南1-10-1 ザ タワーズ ウエスト45階",
      featured_image: `${WP}/2024/01/ilink-town-11.jpg`,
      money: "無料",
      height: "150m",
      hours: "9:00～22:00（展望デッキは21:00まで）",
      station:
        '<ul><li>JR「市川駅」南口より徒歩約3分</li></ul>',
      category: { id: "dummy-chiba", name: "市川市", slug: "ichikawa", created_at: "" },
      category_id: "dummy-chiba",
    }),

    // ========== 公園・広場 ==========
    spot({
      id: "dummy-koume",
      slug: "koume-park",
      title: "小梅児童公園",
      type: "spot",
      address: "東京都墨田区向島 1-33-3",
      featured_image: `${WP}/2024/04/koume-park-2.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東武スカイツリーライン「とうきょうスカイツリー」駅 徒歩1分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-skytree-parking",
      slug: "skytree-bicycle-parking",
      title: "スカイツリー自転車駐車場屋上広場",
      type: "spot",
      address: "東京都墨田区押上1-8 押上駅前自転車駐車場",
      featured_image: `${WP}/2023/01/skytree-parking-01-1.jpg`,
      money: "無料",
      hours: "9:00 ~ 20:00",
      station:
        '<ul><li>都営浅草線「押上駅」から徒歩約3分</li><li>東武伊勢崎線「とうきょうスカイツリー駅」徒歩約4分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-nishi-jikken",
      slug: "nishi-jikken-bridge",
      title: "西十間橋",
      type: "spot",
      address: "東京都墨田区業平 5-12-16",
      featured_image: `${WP}/2023/01/west-jikken-bridge-02.jpg`,
      money: "無料",
      hours: "24時間",
      station:
        '<ul><li>東武伊勢崎線「押上」徒歩7分</li><li>都営浅草線「押上駅」徒歩7分</li><li>東京メトロ半蔵門線「押上駅」徒歩7分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-arakawa-kinegawa",
      slug: "arakawa-river-side",
      title: "荒川河川敷（木根川橋野球場）",
      type: "spot",
      address: "東京都葛飾区東四つ木3丁目",
      featured_image: `${WP}/2023/01/arakawa-yotugibashi-07.jpg`,
      money: "無料",
      hours: "24時間",
      station:
        '<ul><li>京成押上線「四ツ木駅」から徒歩約9分</li></ul>',
      category: { id: "dummy-katsushika", name: "葛飾区", slug: "katsushika", created_at: "" },
      category_id: "dummy-katsushika",
    }),
    spot({
      id: "dummy-kameido",
      slug: "kameido-shrine",
      title: "亀戸天神社",
      type: "spot",
      address: "東京都江東区亀戸 3-6-1",
      featured_image: `${WP}/2024/04/kameido-shrine-1.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>錦糸町駅北口より徒歩15分</li><li>亀戸駅北口より徒歩15分</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-sumida-park",
      slug: "sumida-park",
      title: "墨田区立隅田公園",
      type: "spot",
      address: "東京都墨田区向島 1-2",
      featured_image: `${WP}/2023/12/smuda-park-2.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東武スカイツリーライン / 都営浅草線 / 東京メトロ銀座線「浅草駅」より徒歩5分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-komagata-east",
      slug: "komagatabashi-bridge-intersection",
      title: "駒形橋東詰交差点",
      type: "spot",
      address: "東京都墨田区東駒形 1丁目",
      featured_image: `${WP}/2023/02/komagatabashi-bridge-intersection-04.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>都営浅草線「本所吾妻橋駅」から徒歩約4分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-sakurabashi",
      slug: "sakurabashi-bridge",
      title: "桜橋",
      type: "spot",
      address: "東京都墨田区向島 5-1-1",
      featured_image: `${WP}/2023/01/sakura-bridge-04.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東武伊勢崎線「浅草駅」から徒歩18分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-kuramaebashi",
      slug: "kuramae-bridge",
      title: "蔵前橋",
      type: "spot",
      address: "東京都台東区蔵前 2-1",
      featured_image: `${WP}/2023/12/kuramae-bridge-7.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>都営浅草線「蔵前駅」から徒歩約6分</li><li>都営大江戸線「蔵前駅」から徒歩約7分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
    }),
    spot({
      id: "dummy-makurabashi",
      slug: "makura-bridge",
      title: "枕橋",
      type: "spot",
      address: "東京都墨田区19",
      featured_image: `${WP}/2023/12/makura-bridge-3.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>本所吾妻橋駅A3より徒歩4分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-ryogoku-bridge",
      slug: "ryougoku-bridge",
      title: "両国橋",
      type: "spot",
      address: "東京都墨田区両国 1丁目11",
      featured_image: `${WP}/2024/01/ryougoku-bridge-4.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>JR総武線「両国駅」より徒歩約10分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-ishikawajima",
      slug: "ishikawajima-paris-park",
      title: "石川島公園「パリ広場」",
      type: "spot",
      address: "東京都中央区佃 2-1-5",
      featured_image: `${WP}/2023/08/paris-park-1.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東京メトロ有楽町線、都営大江戸線「月島駅」6番出口から徒歩10分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
    }),
    spot({
      id: "dummy-sumidagawa-ohashi",
      slug: "symida-river-bridge",
      title: "隅田川大橋",
      type: "spot",
      address: "東京都中央区日本橋箱崎町",
      featured_image: `${WP}/2023/01/smida-river-bridge-2.jpg`,
      money: "無料",
      hours: "24時間",
      station:
        '<ul><li>メトロ半蔵門線「水天宮前駅」約7分</li><li>メトロ日比谷線ほか「茅場町駅」から徒歩約11分</li><li>メトロ東西線ほか「門前仲町駅」から徒歩約11分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
    }),
    spot({
      id: "dummy-shioiri",
      slug: "shioiri-park",
      title: "汐入公園",
      type: "spot",
      address: "東京都荒川区南千住 8丁目",
      featured_image: `${WP}/2023/01/shioiri-park-01-1.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>JR常磐線・東京メトロ日比谷線・つくばエクスプレス「南千住」駅から徒歩12分</li></ul>',
      category: { id: "dummy-arakawa", name: "荒川区", slug: "arakawa", created_at: "" },
      category_id: "dummy-arakawa",
    }),
    spot({
      id: "dummy-tobu-bridge",
      slug: "tobu-bridge",
      title: "東武橋",
      type: "spot",
      address: "東京都墨田区向島 1-32-12",
      featured_image: `${WP}/2023/02/tobu-bridge-01.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東武伊勢崎線（東武スカイツリーライン）「とうきょうスカイツリー駅」1番出口から徒歩約1分</li><li>都営浅草線「押上（スカイツリー前）駅」から徒歩約3分</li><li>東京メトロ半蔵門線「押上駅」から徒歩約3分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-fureai",
      slug: "fureai-bridge",
      title: "旧中川河川敷・ふれあい橋",
      type: "spot",
      address: "東京都江戸川区平井 7-34",
      featured_image: `${WP}/2024/02/fureai-bridge-2.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>JR総武線「平井駅」南口より徒歩約15分</li></ul>',
      category: { id: "dummy-edogawa", name: "江戸川区", slug: "edogawa", created_at: "" },
      category_id: "dummy-edogawa",
    }),
  ],
  "tokyo-station": [
    // ========== ホテル ==========
    spot({
      id: "dummy-metropolitan-marunouchi",
      slug: "hotel-metropolitan-marunouchi",
      title: "ホテルメトロポリタン丸の内",
      type: "hotel",
      address: "東京都千代田区丸の内 1-7-12",
      featured_image: `${WP}/2023/03/marunouchi-metropolitan-02-1024x683.jpg`,
      station:
        '<ul><li>JR東京駅日本橋口直結、日本橋口より徒歩1分、八重洲北口改札より徒歩約2分</li><li>東京メトロ東西線大手町駅B7出口より徒歩約1分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
      hotel: {
        id: "dummy-hotel-metropolitan",
        spot_id: "dummy-metropolitan-marunouchi",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-bulgari-tokyo",
      slug: "bulgari-tokyo",
      title: "ブルガリ東京",
      type: "hotel",
      address: "東京都中央区八重洲 2-2-1",
      featured_image: `${WP}/2024/12/bulgari-tokyo-6-1024x683.jpg`,
      station:
        '<ul><li>JR「東京駅」/ 東京メトロ丸の内線「東京駅」地下直結</li><li>東京メトロ銀座線「京橋駅」より徒歩3分</li><li>東京メトロ東西線、銀座線、都営浅草線「日本橋駅」より徒歩6分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
      hotel: {
        id: "dummy-hotel-bulgari",
        spot_id: "dummy-bulgari-tokyo",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    // ========== 展望スポット ==========
    spot({
      id: "dummy-kitte-garden",
      slug: "kitte-garden",
      title: "KITTE丸の内 屋上庭園 KITTEガーデン",
      type: "spot",
      address: "東京都千代田区丸の内2-7-2",
      featured_image: `${WP}/2023/01/kitte-marunouchi-observation-1024x683.jpg`,
      money: "無料",
      hours: "11:00～23:00（日・祝 11:00～22:00）",
      station:
        '<ul><li>JR東京駅丸の内南口から徒歩約1分</li><li>JR京葉線「東京駅」から徒歩約3分</li><li>千代田線「二重橋前駅」から徒歩約2分</li><li>三田線「大手町駅」から徒歩約4分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-kitte-postmaster",
      slug: "former-tokyo-central-post-office",
      title: "KITTE丸の内 旧東京中央郵便局長室",
      type: "spot",
      address: "東京都千代田区丸の内 2-7-2",
      featured_image: `${WP}/2023/07/kitte-3-1024x683.jpg`,
      money: "無料",
      hours: "11:00-21:00 / 11:00-20:00（日祝）",
      station:
        '<ul><li>JR東京駅丸の内南口から徒歩約1分</li><li>JR京葉線「東京駅」から徒歩約3分</li><li>千代田線「二重橋前駅」から徒歩約2分</li><li>三田線「大手町駅」から徒歩約4分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-shin-marunouchi-7f",
      slug: "new-marunouchi-building",
      title: "新丸ビル7階 丸の内ハウス",
      type: "spot",
      address: "東京都千代田区丸の内 1-5-1",
      featured_image: `${WP}/2023/01/new-maru-building-03-1024x683.jpg`,
      money: "無料",
      hours: "平日・土曜 11:00～23:00 日曜・祝日 11:00～22:00",
      station:
        '<ul><li>JR「東京駅丸の内中央口」から徒歩約1分</li><li>千代田線「二重橋前駅」から徒歩約2分</li><li>東西線「大手町駅」から徒歩約4分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-marunouchi-5f",
      slug: "marubiru-f5",
      title: "丸ビル 5階展望デッキ",
      type: "spot",
      address: "東京都千代田区丸の内 2-4-1",
      featured_image: `${WP}/2023/01/marunouchi-building-f5-01-1024x683.jpg`,
      money: "無料",
      hours: "11:00～20:00",
      station:
        '<ul><li>東京駅から約2分</li><li>二重橋前駅から約4分</li><li>大手町駅から約5分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-marunouchi-35f",
      slug: "marubiru-f35",
      title: "丸ビル 35階 展望台",
      type: "spot",
      address: "東京都千代田区丸の内2-4-1",
      featured_image: `${WP}/2023/01/marunouchi-builuding-35-03-1024x683.jpg`,
      money: "無料",
      hours: "平日・土曜日23時まで / 日祝日22時まで",
      station:
        '<ul><li>東京駅から約2分</li><li>二重橋前駅から約4分</li><li>大手町駅から約5分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-midtown-yaesu",
      slug: "tokyo-midtow-yaesu-terrace",
      title: "東京ミッドタウン八重洲 八重洲テラス",
      type: "spot",
      address: "東京都中央区八重洲 2-2-1",
      featured_image: `${WP}/2023/07/yaesdu-mid-1024x683.jpg`,
      money: "無料",
      hours: "9:00〜22:00",
      station:
        '<ul><li>JR「東京駅」/ 東京メトロ丸の内線「東京駅」地下直結</li><li>東京メトロ銀座線「京橋駅」より徒歩3分</li><li>東京メトロ東西線、銀座線、都営浅草線「日本橋駅」より徒歩6分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
    }),
    spot({
      id: "dummy-daimaru-tokyo",
      slug: "daimaru-tokyo",
      title: "大丸東京店 12階展望スポット",
      type: "spot",
      address: "東京都千代田区丸の内1-9-1",
      featured_image: `${WP}/2023/01/daimaru-tokyo-1024x683.jpg`,
      money: "無料",
      hours: "10:00〜20:00",
      station:
        '<ul><li>JR「東京駅」八重洲口直結</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-tokyo-forum",
      slug: "tokyo-international-forum",
      title: "東京国際フォーラム ガラス棟",
      type: "spot",
      address: "東京都千代田区丸の内 3-5-1",
      featured_image: `${WP}/2023/01/tokyo-International-forum-3-1024x683.jpg`,
      money: "無料",
      hours: "7:00～23:30",
      station:
        '<ul><li>JR山手線「有楽町駅」より徒歩1分</li><li>JR山手線「東京駅」より徒歩5分</li><li>丸ノ内線「銀座駅」より徒歩5分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    // ========== 公園・広場・通り ==========
    spot({
      id: "dummy-marunouchi-plaza",
      slug: "tokyo-station-park",
      title: "東京駅丸の内駅前広場",
      type: "spot",
      address: "東京都千代田区丸の内 1丁目",
      featured_image: `${WP}/2023/01/tokyo-station-park-3-1024x683.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東京駅直結</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-gyoko-street",
      slug: "gyoko-street",
      title: "行幸通り",
      type: "spot",
      address: "東京都千代田区丸の内 2-2",
      featured_image: `${WP}/2023/01/gyoko-street-04-1024x683.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>各線「東京駅」丸の内中央口より徒歩1分</li><li>東京メトロ千代田線「二重橋前駅」より徒歩3分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-wadakura",
      slug: "wadakura-park",
      title: "和田倉噴水公園",
      type: "spot",
      address: "東京都千代田区皇居外苑3-1",
      featured_image: `${WP}/2023/06/wakura-park-2-1024x683.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東京メトロ二重橋前から徒歩5分</li><li>東京メトロ大手町から徒歩5分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-hibiya-moat",
      slug: "hibiyabori",
      title: "日比谷濠",
      type: "spot",
      address: "東京都千代田区皇居外苑１",
      featured_image: `${WP}/2023/07/hibiyabori-4-1024x683.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東京メトロ日比谷線、東京メトロ千代田線、都営三田線「日比谷駅」Ｂ２出口から徒歩3分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-sakuradamon",
      slug: "sakuradamon-gate",
      title: "桜田門",
      type: "spot",
      address: "東京都千代田区皇居外苑１",
      featured_image: `${WP}/2023/07/sakuradamon-gate-6-1024x683.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東京メトロ日比谷線、東京メトロ千代田線、都営三田線「日比谷駅」Ｂ２出口から徒歩3分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
  ],
  "observatory": [
    // ========== 有料展望台 ==========
    spot({
      id: "dummy-obs-tokyo-tower",
      slug: "tokyo-tower-observatory",
      title: "東京タワー展望台",
      type: "spot",
      address: "東京都港区芝公園 4-2-8",
      featured_image: `${WP}/2023/01/tokyo-station-1-1024x683.jpg`,
      money: "大人1,200円 高校生1,000円 小中学生700円",
      hours: "9:00~22:30（最終入場 22:00）",
      height: "メインデッキ 150m、トップデッキ 250m",
      station: '<ul><li>大江戸線 赤羽橋駅・赤羽橋口から徒歩5分</li><li>日比谷線 神谷町駅・1番出口から徒歩7分</li><li>三田線 御成門駅・A1から徒歩6分</li><li>三田線 芝公園駅・A4から徒歩10分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-obs-skytree",
      slug: "tokyo-skytree-east-tower",
      title: "東京スカイツリー展望台",
      type: "spot",
      address: "東京都墨田区押上 1-1-2",
      featured_image: `${WP}/2023/02/tokyo-skytree-deck-10-1024x683.jpg`,
      money: "平日 天望デッキ2,100円 / セット券3,100円",
      hours: "10:00～21:00（最終入場 20:00）",
      height: "展望回廊 450m、展望デッキ 350m",
      station: '<ul><li>都営地下鉄「押上」駅から徒歩1分</li><li>東武線「とうきょうスカイツリー」駅から徒歩6分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-obs-shibuya-sky",
      slug: "shibuya-sky",
      title: "渋谷スクランブルスクエア 展望台 渋谷スカイ",
      type: "spot",
      address: "東京都渋谷区渋谷 2-24-12",
      featured_image: `${WP}/2023/01/shibuya-sky-window-1024x683.jpg`,
      money: "大人 2,700円〜3,400円",
      hours: "10:00-22:30（最終入場 21:20）",
      height: "約230m",
      station: '<ul><li>渋谷駅から直結</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-obs-city-view",
      slug: "tokyo-city-view",
      title: "六本木ヒルズ展望台 東京シティビュー",
      type: "spot",
      address: "東京都港区六本木 6-10-1",
      featured_image: `${WP}/2023/01/tokyo-city-view-07-1-1024x683.jpg`,
      money: "一般 2,200円",
      hours: "東京シティビュー 10:00～22:00 スカイデッキ 11:00～20:00",
      height: "250メートル",
      station: '<ul><li>日比谷線「六本木駅」1C出口から徒歩3分</li><li>大江戸線「六本木駅」3出口から徒歩6分</li><li>大江戸線「麻布十番駅」7出口から徒歩9分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-obs-hachitama",
      slug: "hachitama-observatory",
      title: "フジテレビ球体展望室 はちたま",
      type: "spot",
      address: "東京都港区台場 2-4-8",
      featured_image: `${WP}/2023/01/hachitama-1024x683.jpg`,
      money: "一般 700円",
      hours: "10:00～18:00",
      height: "100メートル",
      station: '<ul><li>ゆりかもめ線「お台場海浜公園駅」から徒歩3分</li><li>りんかい線「東京テレポート駅」から徒歩5分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-obs-sunshine",
      slug: "sunshine-60",
      title: "サンシャイン60展望台 てんぼうパーク",
      type: "spot",
      address: "東京都豊島区東池袋 3-1-1",
      featured_image: `${WP}/2023/07/sun-shine-city-1-1024x683.jpg`,
      money: "大人（高校生以上）700～1,200円",
      hours: "11:00～21:00",
      height: "251m",
      station: '<ul><li>JR「池袋駅」東口から徒歩約8分</li><li>有楽町線「東池袋駅」6番出口から徒歩約3分</li></ul>',
      category: { id: "dummy-toshima", name: "豊島区", slug: "toshima", created_at: "" },
      category_id: "dummy-toshima",
    }),
    spot({
      id: "dummy-obs-telecom",
      slug: "telecom-center",
      title: "テレコムセンター展望台",
      type: "spot",
      address: "東京都江東区青海 2-5-10",
      featured_image: `${WP}/2023/01/telecom-center-3-1024x683.jpg`,
      money: "大人 500円",
      hours: "15:00~21:00（土日祝 11:00～21:00）",
      height: "99m",
      station: '<ul><li>ゆりかもめ「テレコムセンター駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-obs-azabudai",
      slug: "azabudai-hills",
      title: "麻布台ヒルズ 展望台 スカイロビー",
      type: "spot",
      address: "東京都港区麻布台 1-2-4",
      featured_image: `${WP}/2023/12/azabudai-hills-1-1024x683.jpg`,
      money: "大人 2,000円",
      hours: "10:00～22:00（最終入場 21:30）",
      height: "約330m",
      station: '<ul><li>日比谷線「神谷町駅」から徒歩5分</li><li>南北線「六本木一丁目駅」から徒歩3分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-obs-magnet",
      slug: "shibuya-class",
      title: "マグネットバイ渋谷109 屋上展望台",
      type: "spot",
      address: "東京都渋谷区神南 1-23-10",
      featured_image: `${WP}/2023/07/shibuya-class-02-1024x683.jpg`,
      money: "大人 600円",
      hours: "11:00～23:00",
      height: "",
      station: '<ul><li>各線「渋谷駅」から徒歩3分</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    // ========== 無料展望台 ==========
    spot({
      id: "dummy-obs-tocho",
      slug: "tokyo-metropolitan-government-office-tomin-hiroba",
      title: "東京都庁 南展望室・北展望室",
      type: "spot",
      address: "東京都新宿区西新宿 2-8-1",
      featured_image: `${WP}/2023/01/metropolitan-government-02-1024x683.jpg`,
      money: "無料",
      hours: "北展望台 9:30～17:30 南展望台 9:30～23:00",
      height: "約202m",
      station: '<ul><li>JR「新宿駅」西口から徒歩約10分</li><li>大江戸線「都庁前駅」A4出口から直通</li></ul>',
      category: { id: "dummy-shinjuku", name: "新宿区", slug: "shinjuku", created_at: "" },
      category_id: "dummy-shinjuku",
    }),
    spot({
      id: "dummy-obs-kitte-garden",
      slug: "kitte-garden",
      title: "KITTE 6階 屋上庭園",
      type: "spot",
      address: "東京都千代田区丸の内2-7-2",
      featured_image: `${WP}/2023/01/kitte-garden-observatory-1-1024x683.jpg`,
      money: "無料",
      hours: "11:00～23:00（日・祝 11:00～22:00）",
      station: '<ul><li>JR東京駅丸の内南口から徒歩約1分</li><li>千代田線「二重橋前駅」から徒歩約2分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-obs-funabori",
      slug: "towerhall-funabori",
      title: "タワーホール船堀",
      type: "spot",
      address: "東京都江戸川区船堀 4-1-1",
      featured_image: `${WP}/2023/02/towerha-ll-funabori-observation-1024x683.jpg`,
      money: "無料",
      hours: "展望エレベーター運行時間：9:00～21:30",
      height: "103m",
      station: '<ul><li>都営新宿線「船堀駅」から徒歩約1分</li></ul>',
      category: { id: "dummy-edogawa", name: "江戸川区", slug: "edogawa", created_at: "" },
      category_id: "dummy-edogawa",
    }),
    spot({
      id: "dummy-obs-civic",
      slug: "civic-bunkyo",
      title: "文京シビックセンター 展望ラウンジ",
      type: "spot",
      address: "東京都文京区春日 1-16-21",
      featured_image: `${WP}/2023/12/civic-bunkyo-1-1024x683.jpg`,
      money: "無料",
      hours: "9:00～20:30",
      height: "約105m",
      station: '<ul><li>東京メトロ丸ノ内線・南北線「後楽園」駅より徒歩1分</li><li>都営三田線・大江戸線「春日」駅より徒歩1分</li></ul>',
      category: { id: "dummy-bunkyo", name: "文京区", slug: "bunkyo", created_at: "" },
      category_id: "dummy-bunkyo",
    }),
    spot({
      id: "dummy-obs-maru35",
      slug: "marubiru-f35",
      title: "丸ビル 35階 展望フロア",
      type: "spot",
      address: "東京都千代田区丸の内2-4-1",
      featured_image: `${WP}/2023/01/marunouchi-builuding-35-floor-02-1024x683.jpg`,
      money: "無料",
      hours: "平日・土曜日23時まで / 日祝日22時まで",
      station: '<ul><li>東京駅から約2分</li><li>二重橋前駅から約4分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
    }),
    spot({
      id: "dummy-obs-ebisu",
      slug: "ebis-garden-place-sky-lounge",
      title: "恵比寿ガーデンプレイス 展望台",
      type: "spot",
      address: "東京都渋谷区恵比寿 4-20",
      featured_image: `${WP}/2023/01/ebis-garden-place-observation-1024x683.jpg`,
      money: "無料",
      hours: "11:00～20:00",
      height: "約160m",
      station: '<ul><li>JR「恵比寿駅」東口改札から徒歩5分</li><li>日比谷線「恵比寿駅」1番出口から徒歩7分</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-obs-carrot",
      slug: "carrot-tower-observation",
      title: "キャロットタワー 展望ロビー",
      type: "spot",
      address: "東京都世田谷区太子堂 4-1-1",
      featured_image: `${WP}/2023/02/carrot-tower-02-1024x683.jpg`,
      money: "無料",
      hours: "9:30～23:00",
      height: "約126m",
      station: '<ul><li>東急田園都市線「三軒茶屋駅」直結</li></ul>',
      category: { id: "dummy-setagaya", name: "世田谷区", slug: "setagaya", created_at: "" },
      category_id: "dummy-setagaya",
    }),
    spot({
      id: "dummy-obs-haneda",
      slug: "haneda-airport",
      title: "羽田空港第一ターミナル 展望デッキ",
      type: "spot",
      address: "東京都大田区羽田空港 3-3-2",
      featured_image: `${WP}/2023/12/haneda-airport-7-1024x683.jpg`,
      money: "無料",
      hours: "6:30～22:00",
      station: '<ul><li>東京モノレール「羽田空港第1ターミナル駅」直結</li><li>京急線「羽田空港第1・第2ターミナル駅」から徒歩約5分</li></ul>',
      category: { id: "dummy-ota", name: "大田区", slug: "ota", created_at: "" },
      category_id: "dummy-ota",
    }),
    spot({
      id: "dummy-obs-caretta",
      slug: "caretta-shiodome-sky-view",
      title: "カレッタ汐留 SKY VIEW",
      type: "spot",
      address: "東京都港区東新橋1-8-1",
      featured_image: `${WP}/2023/01/caretta-floor-1024x683.jpg`,
      money: "無料",
      hours: "11:00～23:00",
      height: "約210m",
      station: '<ul><li>JR「新橋駅」から徒歩4分</li><li>ゆりかもめ「汐留駅」から直結</li><li>大江戸線「汐留駅」から徒歩1分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-obs-kabukicho",
      slug: "tokyu-kabukicho-tower",
      title: "歌舞伎町タワー 展望フロア",
      type: "spot",
      address: "東京都新宿区歌舞伎町 1-29-1",
      featured_image: `${WP}/2023/06/kabuki-tower-3-1024x683.jpg`,
      money: "無料",
      hours: "10:00～翌5:00",
      station: '<ul><li>JR「新宿駅」東口から徒歩7分</li><li>西武新宿線「西武新宿駅」から徒歩1分</li></ul>',
      category: { id: "dummy-shinjuku", name: "新宿区", slug: "shinjuku", created_at: "" },
      category_id: "dummy-shinjuku",
    }),
    spot({
      id: "dummy-obs-asakusa-center",
      slug: "asakusa-cultural-tourism-center",
      title: "浅草文化観光センター 展望テラス",
      type: "spot",
      address: "東京都台東区雷門 2-18-9",
      featured_image: `${WP}/2023/02/asakusabunka-terrace-05-1024x683.jpg`,
      money: "無料",
      hours: "9:00～22:00",
      station: '<ul><li>東武線・銀座線・都営浅草線「浅草駅」から徒歩1分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
    }),
    spot({
      id: "dummy-obs-kitatopia",
      slug: "kitatopia",
      title: "北とぴあ展望ロビー",
      type: "spot",
      address: "東京都北区王子 1-11-1",
      featured_image: `${WP}/2023/02/kita-topia-window-02-1024x683.jpg`,
      money: "無料",
      hours: "8:30～22:00",
      height: "約88m",
      station: '<ul><li>JR京浜東北線「王子駅」北口から徒歩2分</li><li>南北線「王子駅」5番出口から直結</li></ul>',
      category: { id: "dummy-kita", name: "北区", slug: "kita", created_at: "" },
      category_id: "dummy-kita",
    }),
    spot({
      id: "dummy-obs-nerima",
      slug: "nerima-ward-office",
      title: "練馬区役所本庁舎 展望ロビー",
      type: "spot",
      address: "東京都練馬区豊玉北 6-12-1",
      featured_image: `${WP}/2023/11/nerima-ward-office-1-1024x683.jpg`,
      money: "無料",
      hours: "9:00～21:30",
      height: "約80m",
      station: '<ul><li>西武池袋線・有楽町線「練馬駅」西口から徒歩5分</li><li>大江戸線「練馬駅」A2出口から徒歩5分</li></ul>',
      category: { id: "dummy-nerima", name: "練馬区", slug: "nerima", created_at: "" },
      category_id: "dummy-nerima",
    }),
    spot({
      id: "dummy-obs-newoman",
      slug: "newoman-takanawa",
      title: "ニュウマン高輪 LUFTBAUM",
      type: "spot",
      address: "東京都港区高輪 2-21-1",
      featured_image: `${WP}/2025/09/newoman-4.jpg-20-17-07-049-1024x683.jpg`,
      money: "無料",
      hours: "11:00～21:00",
      station: '<ul><li>JR「高輪ゲートウェイ駅」直結</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-obs-east-tower",
      slug: "tokyo-skytree-east-tower",
      title: "スカイツリーイーストタワー 展望フロア",
      type: "spot",
      address: "東京都墨田区押上1-1-2",
      featured_image: `${WP}/2023/01/skytree-east-tower-05-1024x683.jpg`,
      money: "無料",
      hours: "8:00～23:00",
      station: '<ul><li>都営浅草線「押上駅」A3出口から徒歩1分</li><li>東武線「とうきょうスカイツリー駅」から徒歩3分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
    }),
    spot({
      id: "dummy-obs-ilink",
      slug: "ilink-town",
      title: "アイ・リンクタウン展望施設",
      type: "spot",
      address: "千葉県市川市市川南1-10-1 ザ タワーズ ウエスト45階",
      featured_image: `${WP}/2024/01/ilink-town-4-1024x683.jpg`,
      money: "無料",
      hours: "9:00～22:00",
      station: '<ul><li>JR総武線「市川駅」南口直結</li></ul>',
      category: { id: "dummy-ichikawa", name: "市川市", slug: "ichikawa", created_at: "" },
      category_id: "dummy-ichikawa",
    }),
  ],
  "hotel": [
    spot({
      id: "dummy-hotel-prince",
      slug: "the-prince-park-tower-tokyo",
      title: "ザ・プリンス パークタワー東京",
      type: "hotel",
      address: "東京都港区芝公園4-8-1",
      featured_image: `${WP}/2023/01/prince-hotel-room-01-1024x683.jpg`,
      station:
        '<ul><li>都営三田線「芝公園駅」A4出口から徒歩3分</li><li>都営大江戸線「赤羽橋駅」から徒歩2分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
      hotel: {
        id: "dummy-hotel-prince-h",
        spot_id: "dummy-hotel-prince",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-andaz",
      slug: "andaz-tokyo-toranomon-hills",
      title: "アンダーズ東京 虎ノ門ヒルズ",
      type: "hotel",
      address: "東京都港区虎ノ門1-23-4",
      featured_image: `${WP}/2023/01/underz-tokyo-01-1024x683.jpg`,
      station:
        '<ul><li>東京メトロ日比谷線「虎ノ門ヒルズ駅」直結</li><li>東京メトロ銀座線「虎ノ門駅」から徒歩5分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
      hotel: {
        id: "dummy-hotel-andaz-h",
        spot_id: "dummy-hotel-andaz",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-parkhotel",
      slug: "park-hotel-tokyo",
      title: "パークホテル東京",
      type: "hotel",
      address: "東京都港区東新橋1-7-1",
      featured_image: `${WP}/2023/08/park-hotel-1-1024x683.jpg`,
      station:
        '<ul><li>JR・都営浅草線「新橋駅」から徒歩7分</li><li>ゆりかもめ「汐留駅」から徒歩1分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
      hotel: {
        id: "dummy-hotel-parkhotel-h",
        spot_id: "dummy-hotel-parkhotel",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-metropolitan",
      slug: "hotel-metropolitan-marunouchi",
      title: "ホテルメトロポリタン丸の内",
      type: "hotel",
      address: "東京都千代田区丸の内1-7-12",
      featured_image: `${WP}/2023/03/marunouchi-metropolitan-08-1024x683.jpg`,
      station: '<ul><li>JR「東京駅」日本橋口直結</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
      hotel: {
        id: "dummy-hotel-metro-h",
        spot_id: "dummy-hotel-metropolitan",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-grandarc",
      slug: "grandarc",
      title: "ホテルグランドアーク半蔵門",
      type: "hotel",
      address: "東京都千代田区隼町1-1",
      featured_image: `${WP}/2025/03/grandarc-2-1024x683.jpg`,
      station:
        '<ul><li>東京メトロ半蔵門線「半蔵門駅」1番出口から徒歩2分</li></ul>',
      category: { id: "dummy-chiyoda", name: "千代田区", slug: "chiyoda", created_at: "" },
      category_id: "dummy-chiyoda",
      hotel: {
        id: "dummy-hotel-grandarc-h",
        spot_id: "dummy-hotel-grandarc",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-bulgari",
      slug: "bulgari-tokyo",
      title: "ブルガリ東京",
      type: "hotel",
      address: "東京都中央区八重洲2-2-1",
      featured_image: `${WP}/2024/12/bulgari-tokyo-1-1024x683.jpg`,
      station: '<ul><li>JR「東京駅」八重洲南口から徒歩3分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
      hotel: {
        id: "dummy-hotel-bulgari-h",
        spot_id: "dummy-hotel-bulgari",
        checkin: "15:00",
        checkout: "12:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: null,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-keio",
      slug: "keio-plaza",
      title: "京王プラザホテル",
      type: "hotel",
      address: "東京都新宿区西新宿2-2-1",
      featured_image: `${WP}/2023/07/keio-praza-01-1024x682.jpg`,
      station:
        '<ul><li>JR「新宿駅」西口から徒歩5分</li><li>都営大江戸線「都庁前駅」から徒歩1分</li></ul>',
      category: { id: "dummy-shinjuku", name: "新宿区", slug: "shinjuku", created_at: "" },
      category_id: "dummy-shinjuku",
      hotel: {
        id: "dummy-hotel-keio-h",
        spot_id: "dummy-hotel-keio",
        checkin: "14:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-toyosu",
      slug: "mitsuitoyosu-premier",
      title: "三井ガーデンホテル豊洲プレミア",
      type: "hotel",
      address: "東京都江東区豊洲2-2-1",
      featured_image: `${WP}/2023/03/mitsui-garden-toyosu-1-1024x683.jpg`,
      station: '<ul><li>東京メトロ有楽町線「豊洲駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
      hotel: {
        id: "dummy-hotel-toyosu-h",
        spot_id: "dummy-hotel-toyosu",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-lavista",
      slug: "la_tokyobay",
      title: "ラビスタ東京ベイ",
      type: "hotel",
      address: "東京都江東区豊洲6-4-40",
      featured_image: `${WP}/2023/12/lavista-tokyobay-13.jpg`,
      station: '<ul><li>ゆりかもめ「市場前駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
      hotel: {
        id: "dummy-hotel-lavista-h",
        spot_id: "dummy-hotel-lavista",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-creston",
      slug: "ginza-crestonhotel",
      title: "銀座クレストン",
      type: "hotel",
      address: "東京都中央区明石町8-1",
      featured_image: `${WP}/2023/01/ginza-creston-4-1024x683.jpg`,
      station:
        '<ul><li>東京メトロ日比谷線「築地駅」3番出口から徒歩3分</li><li>東京メトロ有楽町線「新富町駅」4番出口から徒歩6分</li></ul>',
      category: { id: "dummy-chuo", name: "中央区", slug: "chuo", created_at: "" },
      category_id: "dummy-chuo",
      hotel: {
        id: "dummy-hotel-creston-h",
        spot_id: "dummy-hotel-creston",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-interconti",
      slug: "interconti-tokyo-bay",
      title: "インターコンチネンタル東京ベイ",
      type: "hotel",
      address: "東京都港区海岸1-16-2",
      featured_image: `${WP}/2023/07/interconti-1-1024x683.jpg`,
      station:
        '<ul><li>JR「浜松町駅」から無料シャトルバスで約10分</li><li>ゆりかもめ「竹芝駅」直結</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
      hotel: {
        id: "dummy-hotel-interconti-h",
        spot_id: "dummy-hotel-interconti",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-washington",
      slug: "washington-hotels-ariake",
      title: "東京ベイ有明ワシントンホテル",
      type: "hotel",
      address: "東京都江東区有明3-7-11",
      featured_image: `${WP}/2024/11/washington-ariake-2-1024x683.jpg`,
      station:
        '<ul><li>りんかい線「国際展示場駅」から徒歩3分</li><li>ゆりかもめ「有明駅」から徒歩3分</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
      hotel: {
        id: "dummy-hotel-washington-h",
        spot_id: "dummy-hotel-washington",
        checkin: "14:00",
        checkout: "10:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-wing",
      slug: "wing-international-select-asakusa-komagata",
      title: "ウィングインターナショナルセレクト浅草駒形",
      type: "hotel",
      address: "東京都台東区駒形1-13-7",
      featured_image: `${WP}/2023/03/wing-asakusa-4-1024x683.jpg`,
      station:
        '<ul><li>都営浅草線「浅草駅」A1出口から徒歩1分</li><li>都営大江戸線「蔵前駅」A6出口から徒歩5分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "dummy-hotel-wing-h",
        spot_id: "dummy-hotel-wing",
        checkin: "15:00",
        checkout: "10:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-asakusa-view",
      slug: "asakusa-view-hotel",
      title: "浅草ビューホテル",
      type: "hotel",
      address: "東京都台東区西浅草3-17-1",
      featured_image: `${WP}/2023/07/asakusa-view-3-1024x683.jpg`,
      station:
        '<ul><li>つくばエクスプレス「浅草駅」直結</li><li>東京メトロ銀座線「田原町駅」から徒歩7分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "dummy-hotel-asakusa-view-h",
        spot_id: "dummy-hotel-asakusa-view",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-kanzashi",
      slug: "the-kanzashi-tokyo-asakusa",
      title: "THE KANZASHI TOKYO ASAKUSA",
      type: "hotel",
      address: "東京都台東区花川戸1-11-1",
      featured_image: `${WP}/2024/06/kanzashi-asakusa-1-1024x683.jpg`,
      station:
        '<ul><li>東武線・銀座線・都営浅草線「浅草駅」から徒歩2分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "dummy-hotel-kanzashi-h",
        spot_id: "dummy-hotel-kanzashi",
        checkin: "15:00",
        checkout: "10:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-gate",
      slug: "the-gate-hotel-kaminarimon-gate-by-hulic",
      title: "The Gate Hotel 雷門 by HULIC",
      type: "hotel",
      address: "東京都台東区雷門2-16-11",
      featured_image: `${WP}/2023/06/gate-hotel-2-1024x683.jpg`,
      station:
        '<ul><li>東武線・銀座線・都営浅草線「浅草駅」から徒歩2分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
      hotel: {
        id: "dummy-hotel-gate-h",
        spot_id: "dummy-hotel-gate",
        checkin: "14:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-apa-ryogoku",
      slug: "apa-hotel-ryogokueki-tower",
      title: "アパホテル 両国駅タワー",
      type: "hotel",
      address: "東京都墨田区横網1-11-10",
      featured_image: `${WP}/2023/10/apa-ryogoku-1-1024x683.jpg`,
      station:
        '<ul><li>JR総武線「両国駅」西口直結</li><li>都営大江戸線「両国駅」A1出口から徒歩5分</li></ul>',
      category: { id: "dummy-sumida", name: "墨田区", slug: "sumida", created_at: "" },
      category_id: "dummy-sumida",
      hotel: {
        id: "dummy-hotel-apa-ryogoku-h",
        spot_id: "dummy-hotel-apa-ryogoku",
        checkin: "15:00",
        checkout: "10:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-apa-yokohama",
      slug: "yokohama-bay-tower",
      title: "アパホテル横浜ベイタワー",
      type: "hotel",
      address: "神奈川県横浜市中区万代町2-3-7",
      featured_image: `${WP}/2023/10/apa-yokohama-1-1024x683.jpg`,
      station:
        '<ul><li>みなとみらい線「元町・中華街駅」3番出口から徒歩3分</li></ul>',
      category: { id: "dummy-yokohama", name: "横浜", slug: "yokohama", created_at: "" },
      category_id: "dummy-yokohama",
      hotel: {
        id: "dummy-hotel-apa-yokohama-h",
        spot_id: "dummy-hotel-apa-yokohama",
        checkin: "15:00",
        checkout: "10:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
    spot({
      id: "dummy-hotel-otani-yokohama",
      slug: "new-otani-inn-yokohama-premium",
      title: "ニューオータニイン横浜プレミアム",
      type: "hotel",
      address: "神奈川県横浜市中区桜木町1-1-7",
      featured_image: `${WP}/2023/10/new-otani-yokohama-1-1024x683.jpg`,
      station: '<ul><li>JR「桜木町駅」新南口直結</li></ul>',
      category: { id: "dummy-yokohama", name: "横浜", slug: "yokohama", created_at: "" },
      category_id: "dummy-yokohama",
      hotel: {
        id: "dummy-hotel-otani-yokohama-h",
        spot_id: "dummy-hotel-otani-yokohama",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-hotel-navios",
      slug: "navios-yokohama",
      title: "ナビオス横浜",
      type: "hotel",
      address: "神奈川県横浜市中区新港2-1-1",
      featured_image: `${WP}/2024/01/navios-yokohama-2-1024x683.jpg`,
      station:
        '<ul><li>みなとみらい線「馬車道駅」6番出口から徒歩3分</li></ul>',
      category: { id: "dummy-yokohama", name: "横浜", slug: "yokohama", created_at: "" },
      category_id: "dummy-yokohama",
      hotel: {
        id: "dummy-hotel-navios-h",
        spot_id: "dummy-hotel-navios",
        checkin: "15:00",
        checkout: "10:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: null,
      },
    }),
  ],
  "rainbow-bridge": [
    spot({
      id: "dummy-rb-lavista",
      slug: "la_tokyobay",
      title: "ラビスタ東京ベイ",
      type: "hotel",
      address: "東京都江東区豊洲6-4-40",
      featured_image: `${WP}/2023/12/lavista-tokyobay-13.jpg`,
      station: '<ul><li>ゆりかもめ「市場前駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
      hotel: {
        id: "dummy-rb-lavista-h",
        spot_id: "dummy-rb-lavista",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-rb-toyosu-premier",
      slug: "mitsuitoyosu-premier",
      title: "三井ガーデンホテル豊洲プレミア",
      type: "hotel",
      address: "東京都江東区豊洲2-2-1",
      featured_image: `${WP}/2023/03/mitsui-garden-toyosu-5-1024x683.jpg`,
      station: '<ul><li>東京メトロ有楽町線「豊洲駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
      hotel: {
        id: "dummy-rb-toyosu-h",
        spot_id: "dummy-rb-toyosu-premier",
        checkin: "15:00",
        checkout: "11:00",
        amenity: null,
        affiliate_1: aff.rakuten,
        affiliate_2: aff.booking,
        affiliate_3: aff.jaran,
        affiliate_4: aff.ikkyu,
      },
    }),
    spot({
      id: "dummy-rb-hachitama",
      slug: "hachitama-observatory",
      title: "球体展望室 はちたま",
      type: "spot",
      address: "東京都港区台場2-4-8",
      featured_image: `${WP}/2023/01/hachitama-rainbow-1024x683.jpg`,
      money: "700円",
      hours: "10:00〜18:00",
      height: "約123m",
      station:
        '<ul><li>ゆりかもめ「台場駅」から徒歩3分</li><li>りんかい線「東京テレポート駅」から徒歩5分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-tokyotower",
      slug: "tokyo-tower-observatory",
      title: "東京タワー展望台",
      type: "spot",
      address: "東京都港区芝公園4-2-8",
      featured_image: `${WP}/2023/01/tokyo-tower-main-deck-04-1024x683.jpg`,
      money: "大人1,200円",
      hours: "9:00〜22:30（最終入場 22:00）",
      height: "メインデッキ 150m、トップデッキ 250m",
      station:
        '<ul><li>大江戸線「赤羽橋駅」赤羽橋口から徒歩5分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-telecom",
      slug: "telecom-center",
      title: "テレコムセンター展望ロビー",
      type: "spot",
      address: "東京都江東区青海2-5-10",
      featured_image: `${WP}/2023/01/telecom-center-rainbow-1024x683.jpg`,
      money: "500円",
      hours: "平日 15:00〜20:00、土日祝 11:00〜20:00",
      height: "約99m",
      station: '<ul><li>ゆりかもめ「テレコムセンター駅」直結</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-rb-caretta",
      slug: "caretta-shiodome-sky-view",
      title: "カレッタ汐留 SKY VIEW",
      type: "spot",
      address: "東京都港区東新橋1-8-1",
      featured_image: `${WP}/2023/01/caretta-floor-1024x683.jpg`,
      money: "無料",
      hours: "11:00〜23:00",
      height: "約210m",
      station:
        '<ul><li>JR「新橋駅」から徒歩4分</li><li>ゆりかもめ「汐留駅」から直結</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-ariake",
      slug: "ariake-sports-center",
      title: "有明スポーツセンター展望回廊",
      type: "spot",
      address: "東京都江東区有明2-3-5",
      featured_image: `${WP}/2023/01/ariake-sports-center-1024x683.jpg`,
      money: "無料",
      hours: "8:30〜22:00",
      station:
        '<ul><li>ゆりかもめ「お台場海浜公園駅」から徒歩10分</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-rb-azabudai",
      slug: "azabudai-hills",
      title: "麻布台ヒルズ スカイロビー",
      type: "spot",
      address: "東京都港区麻布台1-3-1",
      featured_image: `${WP}/2024/02/azabudai-hills-1-1024x683.jpg`,
      money: "無料（カフェ利用必要）",
      hours: "平日 10:00〜21:00、土日祝 9:00〜21:00",
      height: "約325m",
      station: '<ul><li>東京メトロ日比谷線「神谷町駅」直結</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-newoman",
      slug: "newoman-takanawa",
      title: "ニュウマン高輪 LUFTBAUM",
      type: "spot",
      address: "東京都港区高輪2-21-1",
      featured_image: `${WP}/2025/09/newoman-4.jpg-20-17-07-049-1024x683.jpg`,
      money: "無料",
      hours: "11:00〜21:00",
      station: '<ul><li>JR「高輪ゲートウェイ駅」直結</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-promenade",
      slug: "rainbow-bridge-promenade",
      title: "レインボーブリッジ遊歩道",
      type: "spot",
      address: "東京都港区海岸3-33-19",
      featured_image: `${WP}/2023/01/rainbow-bridge-promenade-1024x683.jpg`,
      money: "無料",
      hours: "4月-10月 9:00〜21:00、11月-3月 10:00〜18:00",
      station:
        '<ul><li>ゆりかもめ「芝浦ふ頭駅」から徒歩5分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-odaiba",
      slug: "odaiba-seaside-park",
      title: "お台場海浜公園",
      type: "spot",
      address: "東京都港区台場1-4",
      featured_image: `${WP}/2023/01/odaiba-seaside-park-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「お台場海浜公園駅」から徒歩3分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-loop",
      slug: "shibaura-loop-bridge",
      title: "芝浦ループ橋エリア",
      type: "spot",
      address: "東京都港区海岸3丁目",
      featured_image: `${WP}/2023/01/shibaura-loop-bridge-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「芝浦ふ頭駅」から徒歩9分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-futo",
      slug: "shibaura-futo-park",
      title: "芝浦南ふ頭公園",
      type: "spot",
      address: "東京都港区海岸3-33-20",
      featured_image: `${WP}/2023/01/shibaura-futo-park-1024x683.jpg`,
      money: "無料",
      hours: "8:00〜21:00",
      station:
        '<ul><li>ゆりかもめ「芝浦ふ頭駅」から徒歩5分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-daiba3",
      slug: "daisandaiba",
      title: "台場公園（第三台場）",
      type: "spot",
      address: "東京都港区台場1-10",
      featured_image: `${WP}/2023/01/daisandaiba-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「お台場海浜公園駅」から徒歩15分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-gururi",
      slug: "toyosu-gururi-park",
      title: "豊洲ぐるり公園",
      type: "spot",
      address: "東京都江東区豊洲6-1",
      featured_image: `${WP}/2023/01/toyosu-gururi-rainbow-06-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「市場前駅」から徒歩5分</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-rb-fujimi",
      slug: "fujimibashi-bridge",
      title: "富士見橋",
      type: "spot",
      address: "東京都江東区豊洲6丁目",
      featured_image: `${WP}/2023/01/fujimibashi-bridge-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「市場前駅」から徒歩5分</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
    spot({
      id: "dummy-rb-baybreeze",
      slug: "bay-breeze-garden",
      title: "ベイブリーズガーデン",
      type: "spot",
      address: "東京都港区港南3-9",
      featured_image: `${WP}/2023/01/bay-breeze-garden-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>JR「品川駅」から徒歩約18分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-shinagawa",
      slug: "shinagawa-wharf",
      title: "品川埠頭",
      type: "spot",
      address: "東京都港区港南5-10-1",
      featured_image: `${WP}/2023/01/shinagawa-wharf-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「芝浦ふ頭駅」から徒歩約13分</li></ul>',
      category: { id: "dummy-minato", name: "港区", slug: "minato", created_at: "" },
      category_id: "dummy-minato",
    }),
    spot({
      id: "dummy-rb-toyosu-bridge",
      slug: "toyosu-bridge",
      title: "豊洲大橋",
      type: "spot",
      address: "東京都江東区豊洲6丁目",
      featured_image: `${WP}/2023/01/toyosu-bridge-1024x683.jpg`,
      money: "無料",
      hours: "24時間開放",
      station:
        '<ul><li>ゆりかもめ「市場前駅」から徒歩9分</li></ul>',
      category: { id: "dummy-koto", name: "江東区", slug: "koto", created_at: "" },
      category_id: "dummy-koto",
    }),
  ],
  "scramble-intersection": [
    spot({
      id: "dummy-sc-sky",
      slug: "shibuya-sky",
      title: "渋谷スカイ",
      type: "spot",
      address: "東京都渋谷区渋谷2-24-12",
      featured_image: `${WP}/2023/08/shibuya-sky-29-1024x683.jpg`,
      money: "大人2,000円",
      hours: "10:00〜22:30（最終入場 21:20）",
      height: "約230m",
      station: '<ul><li>JR・東京メトロ「渋谷駅」直結</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-sc-niwa",
      slug: "shibu-niwa",
      title: "SHIBU NIWA（渋谷西武屋上）",
      type: "spot",
      address: "東京都渋谷区宇田川町21-1",
      featured_image: `${WP}/2023/06/shibu-niwa-1-1024x683.jpg`,
      money: "無料",
      hours: "11:00〜21:00",
      station: '<ul><li>JR「渋谷駅」ハチ公口から徒歩3分</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-sc-hikarie",
      slug: "shibuya-hikarie",
      title: "渋谷ヒカリエ スカイロビー",
      type: "spot",
      address: "東京都渋谷区渋谷2-21-1",
      featured_image: `${WP}/2023/06/shibuya-hikarie-1-1024x683.jpg`,
      money: "無料",
      hours: "11:00〜23:00",
      station:
        '<ul><li>東京メトロ「渋谷駅」15番出口直結</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
    spot({
      id: "dummy-sc-class",
      slug: "shibuya-class",
      title: "CLASS SHIBUYA",
      type: "spot",
      address: "東京都渋谷区道玄坂1-12-1",
      featured_image: `${WP}/2023/06/shibuya-class-1-1024x683.jpg`,
      money: "要注文",
      hours: "12:00〜24:00",
      station: '<ul><li>JR「渋谷駅」ハチ公口から徒歩3分</li></ul>',
      category: { id: "dummy-shibuya", name: "渋谷区", slug: "shibuya", created_at: "" },
      category_id: "dummy-shibuya",
    }),
  ],
  "illumination": [
    spot({
      id: "dummy-il-marunouchi",
      slug: "marunouchi-illumination",
      title: "丸の内イルミネーション",
      type: "event",
      address: "東京都千代田区丸の内1〜3丁目周辺",
      featured_image: `${WP}/2023/02/marunouchi-illumination-01.jpg`,
      money: "無料",
      hours: "16:00〜24:00",
      station:
        '<ul><li>JR「東京駅」から約2分</li><li>東京メトロ「二重橋前駅」から約4分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-marunouchi",
        spot_id: "dummy-il-marunouchi",
        start_date: "2025-11-13",
        end_date: "2026-02-15",
        place: null,
        event_hour: "16:00~24:00",
      },
    }),
    spot({
      id: "dummy-il-keyaki",
      slug: "roppongi-keyaki-street",
      title: "六本木けやき坂通り イルミネーション",
      type: "event",
      address: "東京都港区六本木6-12",
      featured_image: `${WP}/2023/01/ropponngi-keyaki-street-01.jpg`,
      money: "無料",
      hours: "17:00〜23:00",
      station:
        '<ul><li>東京メトロ日比谷線「六本木駅」1出口から直結</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-keyaki",
        spot_id: "dummy-il-keyaki",
        start_date: "2025-11-04",
        end_date: "2025-12-25",
        place: null,
        event_hour: "17:00~23:00",
      },
    }),
    spot({
      id: "dummy-il-aonodokutsu",
      slug: "aonodokutsu",
      title: "青の洞窟 SHIBUYA",
      type: "event",
      address: "東京都渋谷区神南1-5-11",
      featured_image: `${WP}/2023/12/aono-dokutsu-3.jpg`,
      money: "無料",
      hours: "15:00〜22:00",
      station:
        '<ul><li>JR原宿駅、東京メトロ明治神宮前駅より徒歩10分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-aono",
        spot_id: "dummy-il-aonodokutsu",
        start_date: "2025-12-04",
        end_date: "2025-12-25",
        place: null,
        event_hour: "15:00~22:00",
      },
    }),
    spot({
      id: "dummy-il-ebisu",
      slug: "ebis-garden-place-sky-lounge-illumination",
      title: "恵比寿ガーデンプレイス イルミネーション",
      type: "event",
      address: "東京都渋谷区恵比寿4-20",
      featured_image: `${WP}/2023/12/ebis-4.jpg`,
      money: "無料",
      hours: "16:00〜23:00",
      station:
        '<ul><li>JR山手線「恵比寿駅」から徒歩5分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-ebisu",
        spot_id: "dummy-il-ebisu",
        start_date: "2025-11-08",
        end_date: "2026-03-01",
        place: null,
        event_hour: "16:00~23:00",
      },
    }),
    spot({
      id: "dummy-il-midtown",
      slug: "tokyo-midtown-winter-illumination",
      title: '東京ミッドタウン「光の散歩道」',
      type: "event",
      address: "東京都港区赤坂9-7-1",
      featured_image: `${WP}/2023/12/tokyo-midtown-illumination-2.jpg`,
      money: "無料",
      hours: "17:00〜23:00",
      station:
        '<ul><li>東京メトロ日比谷線「六本木駅」8番出口より直結</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-midtown",
        spot_id: "dummy-il-midtown",
        start_date: "2025-11-13",
        end_date: "2026-02-23",
        place: null,
        event_hour: "17:00~23:00",
      },
    }),
    spot({
      id: "dummy-il-meguro",
      slug: "gotanda-winter-illumination",
      title: "目黒川みんなのイルミネーション",
      type: "event",
      address: "東京都品川区東五反田2-9-11",
      featured_image: `${WP}/2024/11/gotanda-illumination-1-1.jpg`,
      money: "無料",
      hours: "17:00〜22:30",
      station:
        '<ul><li>JR線「五反田駅」から徒歩約3分</li><li>JR線「大崎駅」から徒歩約5分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-meguro",
        spot_id: "dummy-il-meguro",
        start_date: "2025-12-05",
        end_date: "2026-01-31",
        place: null,
        event_hour: "17:00~22:30",
      },
    }),
    spot({
      id: "dummy-il-omotesando",
      slug: "omotesando-illumination",
      title: "表参道イルミネーション",
      type: "event",
      address: "東京都渋谷区神宮前4丁目12",
      featured_image: `${WP}/2023/12/omotesando-illumination-1.jpg`,
      money: "無料",
      hours: "日没〜22:00",
      station:
        '<ul><li>JR「原宿駅」東口から徒歩3分</li><li>東京メトロ「明治神宮前駅」2番口から徒歩4分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-omotesando",
        spot_id: "dummy-il-omotesando",
        start_date: "2025-12-01",
        end_date: "2025-12-28",
        place: null,
        event_hour: "日没~22:00",
      },
    }),
  ],
  "cherry-blossoms": [
    spot({
      id: "dummy-cb-meguro",
      slug: "meguro-river",
      title: "中目黒桜まつり",
      type: "event",
      address: "東京都目黒区中目黒",
      featured_image: `${WP}/2023/03/meguro-river-06.jpg`,
      money: "無料",
      hours: "17:00〜20:00",
      station:
        '<ul><li>東京メトロ日比谷線・東急東横線「中目黒駅」から徒歩1分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-meguro-sakura",
        spot_id: "dummy-cb-meguro",
        start_date: "2025-03-19",
        end_date: "2025-03-30",
        place: null,
        event_hour: "17:00~20:00",
      },
    }),
    spot({
      id: "dummy-cb-gotanda",
      slug: "gotanda-sakura-lightup",
      title: "目黒川さくらのライトアップ",
      type: "event",
      address: "東京都品川区東五反田2-9-11",
      featured_image: `${WP}/2023/03/gotanda-meguro-river-4.jpg`,
      money: "無料",
      hours: "17:00〜21:00",
      station:
        '<ul><li>JR線「五反田駅」から徒歩約3分</li><li>JR線「大崎駅」から徒歩約5分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-gotanda-sakura",
        spot_id: "dummy-cb-gotanda",
        start_date: "2025-03-19",
        end_date: "2025-04-13",
        place: null,
        event_hour: "17:00~21:00",
      },
    }),
    spot({
      id: "dummy-cb-chidorigabuchi",
      slug: "chidorigabuchi",
      title: "千鳥ヶ淵緑道 千代田のさくらまつり",
      type: "event",
      address: "東京都千代田区九段南2丁目〜3番町2",
      featured_image: `${WP}/2023/03/chidorigabuchi-3.jpg`,
      money: "無料",
      hours: "日没〜21:00",
      station:
        '<ul><li>東京メトロ「九段下駅」から徒歩5分</li><li>東京メトロ「半蔵門駅」から徒歩5分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-chidori",
        spot_id: "dummy-cb-chidorigabuchi",
        start_date: "2025-03-28",
        end_date: "2025-04-08",
        place: null,
        event_hour: "日没~21:00",
      },
    }),
    spot({
      id: "dummy-cb-roppongi",
      slug: "roppongi-sakura-street",
      title: "六本木さくら通り 桜のライトアップ",
      type: "event",
      address: "東京都港区六本木6-12",
      featured_image: `${WP}/2023/03/roppongi-sakura-street-01.jpg`,
      money: "無料",
      hours: "17:00〜22:00",
      station:
        '<ul><li>東京メトロ日比谷線「六本木駅」1C出口から徒歩2分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-roppongi-sakura",
        spot_id: "dummy-cb-roppongi",
        start_date: "2025-03-22",
        end_date: "2025-04-15",
        place: null,
        event_hour: "17:00~22:00",
      },
    }),
    spot({
      id: "dummy-cb-mouri",
      slug: "mouri-park",
      title: "毛利庭園 桜のライトアップ",
      type: "event",
      address: "東京都港区六本木6-10-1",
      featured_image: `${WP}/2023/01/mouri-2.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>東京メトロ日比谷線「六本木駅」1C出口 徒歩0分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-mouri",
        spot_id: "dummy-cb-mouri",
        start_date: "2025-03-22",
        end_date: "2025-04-15",
        place: null,
        event_hour: null,
      },
    }),
    spot({
      id: "dummy-cb-midtown",
      slug: "midtown-blossom",
      title: "東京ミッドタウン MIDTOWN BLOSSOM",
      type: "event",
      address: "東京都港区赤坂9-7-1",
      featured_image: `${WP}/2023/03/tokyo-mid-town-01.jpg`,
      money: "無料",
      hours: "17:00〜23:00",
      station:
        '<ul><li>東京メトロ日比谷線「六本木駅」8番出口より直結</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-midtown-blossom",
        spot_id: "dummy-cb-midtown",
        start_date: "2025-03-14",
        end_date: "2025-04-13",
        place: null,
        event_hour: "17:00~23:00",
      },
    }),
    spot({
      id: "dummy-cb-shibuya",
      slug: "shibuya-sakura-street",
      title: "しぶやさくらまつり",
      type: "event",
      address: "東京都渋谷区桜丘町16-12",
      featured_image: `${WP}/2023/03/shibuya-sakura-street-4.jpg`,
      money: "無料",
      hours: "17:00〜23:00",
      station:
        '<ul><li>JR線「渋谷駅」西口から徒歩約5分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-shibuya-sakura",
        spot_id: "dummy-cb-shibuya",
        start_date: "2025-03-24",
        end_date: "2025-04-06",
        place: null,
        event_hour: "17:00~23:00",
      },
    }),
    spot({
      id: "dummy-cb-edo",
      slug: "edo-sakura-street",
      title: "江戸桜通り SAKURA FES NIHONBASHI",
      type: "event",
      address: "東京都中央区日本橋本町1-5",
      featured_image: `${WP}/2023/03/edo-sakura-street-9.jpg`,
      money: "無料",
      hours: "17:00〜23:00",
      station:
        '<ul><li>東京メトロ「三越前駅」・JR「新日本橋駅」直結</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-edo-sakura",
        spot_id: "dummy-cb-edo",
        start_date: "2025-03-19",
        end_date: "2025-04-06",
        place: null,
        event_hour: "17:00~23:00",
      },
    }),
    spot({
      id: "dummy-cb-ueno",
      slug: "ueno-park",
      title: "上野恩賜公園",
      type: "spot",
      address: "東京都台東区上野公園・池之端三丁目",
      featured_image: `${WP}/2024/04/ueno-park-20.jpg`,
      money: "無料",
      hours: "終日開放",
      station:
        '<ul><li>JR「上野駅」より徒歩2分</li><li>京成本線「京成上野駅」より徒歩1分</li></ul>',
      category: { id: "dummy-taito", name: "台東区", slug: "taito", created_at: "" },
      category_id: "dummy-taito",
    }),
    spot({
      id: "dummy-cb-otonashi",
      slug: "otonashigawa-park",
      title: "音無親水公園 夜桜のライトアップ",
      type: "event",
      address: "東京都北区王子本町1-1",
      featured_image: `${WP}/2024/04/otonashi-park-12.jpg`,
      money: "無料",
      hours: "日没〜22:00",
      station:
        '<ul><li>JR王子駅（北口）から徒歩で1分</li><li>南北線王子駅（3番出口）から徒歩で1分</li></ul>',
      category: { id: "dummy-event", name: "イベント", slug: "event", created_at: "" },
      category_id: "dummy-event",
      event: {
        id: "dummy-ev-otonashi",
        spot_id: "dummy-cb-otonashi",
        start_date: "2025-03-15",
        end_date: "2025-04-06",
        place: null,
        event_hour: "日没~22:00",
      },
    }),
  ],
};
