#!/usr/bin/env python3
"""
Parse WordPress WXR export and generate SQL UPDATE statements for luminar_posts.content.

Usage:
    python3 import-luminar-content.py luminar.xml > update-luminar-content.sql
"""

import sys
import re
import xml.etree.ElementTree as ET

NS = {
    "content": "http://purl.org/rss/1.0/modules/content/",
    "wp": "http://wordpress.org/export/1.2/",
    "excerpt": "http://wordpress.org/export/1.2/excerpt/",
}

WP_UPLOAD_URL = "http://nightscape.tokyo/luminar/wp-content/uploads/"
R2_URL = "https://pub-7d430b8241bc4d38b717b9e2905120d8.r2.dev/luminar/uploads/"

SHORTCODE_PATTERNS = [
    # [mini_cta] ... [/mini_cta]  or  [mini_cta]
    re.compile(r'\[mini_cta\b[^\]]*\].*?\[/mini_cta\]', re.DOTALL),
    re.compile(r'\[mini_cta\b[^\]]*\]'),
    # [luminar_sale] ... [/luminar_sale]  or  [luminar_sale]
    re.compile(r'\[luminar_sale\b[^\]]*\].*?\[/luminar_sale\]', re.DOTALL),
    re.compile(r'\[luminar_sale\b[^\]]*\]'),
    # [image_compare before="..." after="..." ...]
    re.compile(r'\[image_compare\b[^\]]*\]'),
]


def clean_content(html: str) -> str:
    # Replace WP upload URLs with R2 URLs
    html = html.replace(WP_UPLOAD_URL, R2_URL)

    # Remove shortcodes
    for pattern in SHORTCODE_PATTERNS:
        html = pattern.sub('', html)

    # Collapse multiple blank lines left by removed shortcodes
    html = re.sub(r'\n{3,}', '\n\n', html)

    return html.strip()


def dollar_quote(text: str) -> str:
    """Wrap text in a PostgreSQL dollar-quote that doesn't appear in the text."""
    tag = "$body$"
    i = 0
    while tag in text:
        tag = f"$body{i}$"
        i += 1
    return f"{tag}{text}{tag}"


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 import-luminar-content.py <wordpress-export.xml>", file=sys.stderr)
        sys.exit(1)

    xml_path = sys.argv[1]

    # Register namespaces to avoid ns0: prefixes in output (not needed for parsing)
    tree = ET.parse(xml_path)
    root = tree.getroot()

    channel = root.find("channel")
    if channel is None:
        print("ERROR: <channel> not found in XML", file=sys.stderr)
        sys.exit(1)

    print("-- Auto-generated by import-luminar-content.py")
    print("-- Run in Supabase SQL Editor after import-luminar.sql\n")

    count = 0
    for item in channel.findall("item"):
        post_type = item.findtext("wp:post_type", namespaces=NS)
        status = item.findtext("wp:status", namespaces=NS)

        if post_type != "post" or status != "publish":
            continue

        slug = item.findtext("wp:post_name", namespaces=NS)
        content_el = item.find("content:encoded", NS)
        raw_content = content_el.text if content_el is not None and content_el.text else ""

        if not slug:
            continue

        cleaned = clean_content(raw_content)
        quoted = dollar_quote(cleaned)

        print(f"UPDATE luminar_posts SET content = {quoted} WHERE slug = '{slug}';")
        print()
        count += 1

    print(f"-- Done: {count} posts updated", file=sys.stderr)


if __name__ == "__main__":
    main()
